package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AccountStatement generated by hbm2java
 */
public class AccountStatement  implements java.io.Serializable {


     private int id;
     private Master master;
     private Integer cardId;
     private Integer month;
     private Integer year;
     private BigDecimal totalPrice;

    public AccountStatement() {
    }

	
    public AccountStatement(int id) {
        this.id = id;
    }
    public AccountStatement(int id, Master master, Integer cardId, Integer month, Integer year, BigDecimal totalPrice) {
       this.id = id;
       this.master = master;
       this.cardId = cardId;
       this.month = month;
       this.year = year;
       this.totalPrice = totalPrice;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public Integer getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }




}


