package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Agent generated by hbm2java
 */
public class Agent  implements java.io.Serializable {


     private int agentId;
     private Agent agent;
     private Area area;
     private Master master;
     private User user;
     private Serializable agentName;
     private Boolean activate;
     private Set agents = new HashSet(0);
     private Set merchants = new HashSet(0);

    public Agent() {
    }

	
    public Agent(int agentId) {
        this.agentId = agentId;
    }
    public Agent(int agentId, Agent agent, Area area, Master master, User user, Serializable agentName, Boolean activate, Set agents, Set merchants) {
       this.agentId = agentId;
       this.agent = agent;
       this.area = area;
       this.master = master;
       this.user = user;
       this.agentName = agentName;
       this.activate = activate;
       this.agents = agents;
       this.merchants = merchants;
    }
   
    public int getAgentId() {
        return this.agentId;
    }
    
    public void setAgentId(int agentId) {
        this.agentId = agentId;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getAgentName() {
        return this.agentName;
    }
    
    public void setAgentName(Serializable agentName) {
        this.agentName = agentName;
    }
    public Boolean getActivate() {
        return this.activate;
    }
    
    public void setActivate(Boolean activate) {
        this.activate = activate;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }
    public Set getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set merchants) {
        this.merchants = merchants;
    }




}


