package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int areaId;
     private Serializable areaName;
     private Set merchants = new HashSet(0);
     private Set agents = new HashSet(0);

    public Area() {
    }

	
    public Area(int areaId) {
        this.areaId = areaId;
    }
    public Area(int areaId, Serializable areaName, Set merchants, Set agents) {
       this.areaId = areaId;
       this.areaName = areaName;
       this.merchants = merchants;
       this.agents = agents;
    }
   
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }
    public Serializable getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(Serializable areaName) {
        this.areaName = areaName;
    }
    public Set getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set merchants) {
        this.merchants = merchants;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }




}


