package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CardType generated by hbm2java
 */
public class CardType  implements java.io.Serializable {


     private int cardTypeId;
     private Serializable cardTypeName;
     private Set cards = new HashSet(0);

    public CardType() {
    }

	
    public CardType(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }
    public CardType(int cardTypeId, Serializable cardTypeName, Set cards) {
       this.cardTypeId = cardTypeId;
       this.cardTypeName = cardTypeName;
       this.cards = cards;
    }
   
    public int getCardTypeId() {
        return this.cardTypeId;
    }
    
    public void setCardTypeId(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }
    public Serializable getCardTypeName() {
        return this.cardTypeName;
    }
    
    public void setCardTypeName(Serializable cardTypeName) {
        this.cardTypeName = cardTypeName;
    }
    public Set getCards() {
        return this.cards;
    }
    
    public void setCards(Set cards) {
        this.cards = cards;
    }




}


