package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Master generated by hbm2java
 */
public class Master  implements java.io.Serializable {


     private int masterId;
     private User user;
     private Serializable masterName;
     private Set cards = new HashSet(0);
     private Set accountStatements = new HashSet(0);
     private Set agents = new HashSet(0);

    public Master() {
    }

	
    public Master(int masterId) {
        this.masterId = masterId;
    }
    public Master(int masterId, User user, Serializable masterName, Set cards, Set accountStatements, Set agents) {
       this.masterId = masterId;
       this.user = user;
       this.masterName = masterName;
       this.cards = cards;
       this.accountStatements = accountStatements;
       this.agents = agents;
    }
   
    public int getMasterId() {
        return this.masterId;
    }
    
    public void setMasterId(int masterId) {
        this.masterId = masterId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Serializable getMasterName() {
        return this.masterName;
    }
    
    public void setMasterName(Serializable masterName) {
        this.masterName = masterName;
    }
    public Set getCards() {
        return this.cards;
    }
    
    public void setCards(Set cards) {
        this.cards = cards;
    }
    public Set getAccountStatements() {
        return this.accountStatements;
    }
    
    public void setAccountStatements(Set accountStatements) {
        this.accountStatements = accountStatements;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }




}


