package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MerchantType generated by hbm2java
 */
public class MerchantType  implements java.io.Serializable {


     private int merchantTypeId;
     private Serializable merchantTypeName;
     private Set merchants = new HashSet(0);

    public MerchantType() {
    }

	
    public MerchantType(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }
    public MerchantType(int merchantTypeId, Serializable merchantTypeName, Set merchants) {
       this.merchantTypeId = merchantTypeId;
       this.merchantTypeName = merchantTypeName;
       this.merchants = merchants;
    }
   
    public int getMerchantTypeId() {
        return this.merchantTypeId;
    }
    
    public void setMerchantTypeId(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }
    public Serializable getMerchantTypeName() {
        return this.merchantTypeName;
    }
    
    public void setMerchantTypeName(Serializable merchantTypeName) {
        this.merchantTypeName = merchantTypeName;
    }
    public Set getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set merchants) {
        this.merchants = merchants;
    }




}


