package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MessageType generated by hbm2java
 */
public class MessageType  implements java.io.Serializable {


     private int messageTypeId;
     private Serializable messageTypeName;
     private Set messages = new HashSet(0);

    public MessageType() {
    }

	
    public MessageType(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    public MessageType(int messageTypeId, Serializable messageTypeName, Set messages) {
       this.messageTypeId = messageTypeId;
       this.messageTypeName = messageTypeName;
       this.messages = messages;
    }
   
    public int getMessageTypeId() {
        return this.messageTypeId;
    }
    
    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    public Serializable getMessageTypeName() {
        return this.messageTypeName;
    }
    
    public void setMessageTypeName(Serializable messageTypeName) {
        this.messageTypeName = messageTypeName;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


