package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private int privilegeId;
     private Serializable privilegeName;
     private Set users = new HashSet(0);

    public Privilege() {
    }

	
    public Privilege(int privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Privilege(int privilegeId, Serializable privilegeName, Set users) {
       this.privilegeId = privilegeId;
       this.privilegeName = privilegeName;
       this.users = users;
    }
   
    public int getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(int privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Serializable getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(Serializable privilegeName) {
        this.privilegeName = privilegeName;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


