package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ReportType generated by hbm2java
 */
public class ReportType  implements java.io.Serializable {


     private int reportTypeId;
     private Serializable reportTypeName;
     private Set reportMasters = new HashSet(0);
     private Set reportMerchants = new HashSet(0);
     private Set reportAgents = new HashSet(0);

    public ReportType() {
    }

	
    public ReportType(int reportTypeId) {
        this.reportTypeId = reportTypeId;
    }
    public ReportType(int reportTypeId, Serializable reportTypeName, Set reportMasters, Set reportMerchants, Set reportAgents) {
       this.reportTypeId = reportTypeId;
       this.reportTypeName = reportTypeName;
       this.reportMasters = reportMasters;
       this.reportMerchants = reportMerchants;
       this.reportAgents = reportAgents;
    }
   
    public int getReportTypeId() {
        return this.reportTypeId;
    }
    
    public void setReportTypeId(int reportTypeId) {
        this.reportTypeId = reportTypeId;
    }
    public Serializable getReportTypeName() {
        return this.reportTypeName;
    }
    
    public void setReportTypeName(Serializable reportTypeName) {
        this.reportTypeName = reportTypeName;
    }
    public Set getReportMasters() {
        return this.reportMasters;
    }
    
    public void setReportMasters(Set reportMasters) {
        this.reportMasters = reportMasters;
    }
    public Set getReportMerchants() {
        return this.reportMerchants;
    }
    
    public void setReportMerchants(Set reportMerchants) {
        this.reportMerchants = reportMerchants;
    }
    public Set getReportAgents() {
        return this.reportAgents;
    }
    
    public void setReportAgents(Set reportAgents) {
        this.reportAgents = reportAgents;
    }




}


