package POJOs;
// Generated Jun 7, 2017 1:31:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private Privilege privilege;
     private String userName;
     private String password;
     private Boolean activate;
     private Set messagesForUserIdSend = new HashSet(0);
     private Set masters = new HashSet(0);
     private Set agents = new HashSet(0);
     private Set messagesForUserIdRecevie = new HashSet(0);
     private Set merchants = new HashSet(0);

    public User() {
    }

	
    public User(int userId) {
        this.userId = userId;
    }
    public User(int userId, Privilege privilege, String userName, String password, Boolean activate, Set messagesForUserIdSend, Set masters, Set agents, Set messagesForUserIdRecevie, Set merchants) {
       this.userId = userId;
       this.privilege = privilege;
       this.userName = userName;
       this.password = password;
       this.activate = activate;
       this.messagesForUserIdSend = messagesForUserIdSend;
       this.masters = masters;
       this.agents = agents;
       this.messagesForUserIdRecevie = messagesForUserIdRecevie;
       this.merchants = merchants;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActivate() {
        return this.activate;
    }
    
    public void setActivate(Boolean activate) {
        this.activate = activate;
    }
    public Set getMessagesForUserIdSend() {
        return this.messagesForUserIdSend;
    }
    
    public void setMessagesForUserIdSend(Set messagesForUserIdSend) {
        this.messagesForUserIdSend = messagesForUserIdSend;
    }
    public Set getMasters() {
        return this.masters;
    }
    
    public void setMasters(Set masters) {
        this.masters = masters;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }
    public Set getMessagesForUserIdRecevie() {
        return this.messagesForUserIdRecevie;
    }
    
    public void setMessagesForUserIdRecevie(Set messagesForUserIdRecevie) {
        this.messagesForUserIdRecevie = messagesForUserIdRecevie;
    }
    public Set getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set merchants) {
        this.merchants = merchants;
    }




}


