package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int accountId;
     private Privilege privilege;
     private String userName;
     private String password;
     private Boolean activate;
     private Set<Master> masters = new HashSet<Master>(0);
     private Set<Agent> agents = new HashSet<Agent>(0);
     private Set<Merchant> merchants = new HashSet<Merchant>(0);

    public Account() {
    }

	
    public Account(int accountId) {
        this.accountId = accountId;
    }
    public Account(int accountId, Privilege privilege, String userName, String password, Boolean activate, Set<Master> masters, Set<Agent> agents, Set<Merchant> merchants) {
       this.accountId = accountId;
       this.privilege = privilege;
       this.userName = userName;
       this.password = password;
       this.activate = activate;
       this.masters = masters;
       this.agents = agents;
       this.merchants = merchants;
    }
   
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActivate() {
        return this.activate;
    }
    
    public void setActivate(Boolean activate) {
        this.activate = activate;
    }
    public Set<Master> getMasters() {
        return this.masters;
    }
    
    public void setMasters(Set<Master> masters) {
        this.masters = masters;
    }
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }




}


