package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int areaId;
     private Serializable areaName;
     private Set<Merchant> merchants = new HashSet<Merchant>(0);
     private Set<Agent> agents = new HashSet<Agent>(0);

    public Area() {
    }

	
    public Area(int areaId) {
        this.areaId = areaId;
    }
    public Area(int areaId, Serializable areaName, Set<Merchant> merchants, Set<Agent> agents) {
       this.areaId = areaId;
       this.areaName = areaName;
       this.merchants = merchants;
       this.agents = agents;
    }
   
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }
    public Serializable getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(Serializable areaName) {
        this.areaName = areaName;
    }
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }




}


