package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * CardType generated by hbm2java
 */
public class CardType  implements java.io.Serializable {


     private int cardTypeId;
     private Serializable cardTypeName;
     private Set<Card> cards = new HashSet<Card>(0);

    public CardType() {
    }

	
    public CardType(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }
    public CardType(int cardTypeId, Serializable cardTypeName, Set<Card> cards) {
       this.cardTypeId = cardTypeId;
       this.cardTypeName = cardTypeName;
       this.cards = cards;
    }
   
    public int getCardTypeId() {
        return this.cardTypeId;
    }
    
    public void setCardTypeId(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }
    public Serializable getCardTypeName() {
        return this.cardTypeName;
    }
    
    public void setCardTypeName(Serializable cardTypeName) {
        this.cardTypeName = cardTypeName;
    }
    public Set<Card> getCards() {
        return this.cards;
    }
    
    public void setCards(Set<Card> cards) {
        this.cards = cards;
    }




}


