package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1



/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private int cardId;
     private CardType cardType;
     private Master master;
     private String cardNumber;

    public Card() {
    }

	
    public Card(int cardId, String cardNumber) {
        this.cardId = cardId;
        this.cardNumber = cardNumber;
    }
    public Card(int cardId, CardType cardType, Master master, String cardNumber) {
       this.cardId = cardId;
       this.cardType = cardType;
       this.master = master;
       this.cardNumber = cardNumber;
    }
   
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }
    public CardType getCardType() {
        return this.cardType;
    }
    
    public void setCardType(CardType cardType) {
        this.cardType = cardType;
    }
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }




}


