package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Master generated by hbm2java
 */
public class Master  implements java.io.Serializable {


     private int masterId;
     private Account account;
     private Serializable masterName;
     private Set<Card> cards = new HashSet<Card>(0);
     private Set<AccountStatement> accountStatements = new HashSet<AccountStatement>(0);
     private Set<Agent> agents = new HashSet<Agent>(0);

    public Master() {
    }

	
    public Master(int masterId) {
        this.masterId = masterId;
    }
    public Master(int masterId, Account account, Serializable masterName, Set<Card> cards, Set<AccountStatement> accountStatements, Set<Agent> agents) {
       this.masterId = masterId;
       this.account = account;
       this.masterName = masterName;
       this.cards = cards;
       this.accountStatements = accountStatements;
       this.agents = agents;
    }
   
    public int getMasterId() {
        return this.masterId;
    }
    
    public void setMasterId(int masterId) {
        this.masterId = masterId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Serializable getMasterName() {
        return this.masterName;
    }
    
    public void setMasterName(Serializable masterName) {
        this.masterName = masterName;
    }
    public Set<Card> getCards() {
        return this.cards;
    }
    
    public void setCards(Set<Card> cards) {
        this.cards = cards;
    }
    public Set<AccountStatement> getAccountStatements() {
        return this.accountStatements;
    }
    
    public void setAccountStatements(Set<AccountStatement> accountStatements) {
        this.accountStatements = accountStatements;
    }
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }




}


