package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MerchantType generated by hbm2java
 */
public class MerchantType  implements java.io.Serializable {


     private int merchantTypeId;
     private Serializable merchantTypeName;
     private Set<Merchant> merchants = new HashSet<Merchant>(0);

    public MerchantType() {
    }

	
    public MerchantType(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }
    public MerchantType(int merchantTypeId, Serializable merchantTypeName, Set<Merchant> merchants) {
       this.merchantTypeId = merchantTypeId;
       this.merchantTypeName = merchantTypeName;
       this.merchants = merchants;
    }
   
    public int getMerchantTypeId() {
        return this.merchantTypeId;
    }
    
    public void setMerchantTypeId(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }
    public Serializable getMerchantTypeName() {
        return this.merchantTypeName;
    }
    
    public void setMerchantTypeName(Serializable merchantTypeName) {
        this.merchantTypeName = merchantTypeName;
    }
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }




}


