package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Merchant generated by hbm2java
 */
public class Merchant  implements java.io.Serializable {


     private int merchantId;
     private Account account;
     private Agent agent;
     private Area area;
     private MerchantType merchantType;
     private Serializable merchantName;
     private Serializable address;
     private Date beginDay;
     private Boolean activate;
     private Set<TransactionDetails> transactionDetailses = new HashSet<TransactionDetails>(0);

    public Merchant() {
    }

	
    public Merchant(int merchantId) {
        this.merchantId = merchantId;
    }
    public Merchant(int merchantId, Account account, Agent agent, Area area, MerchantType merchantType, Serializable merchantName, Serializable address, Date beginDay, Boolean activate, Set<TransactionDetails> transactionDetailses) {
       this.merchantId = merchantId;
       this.account = account;
       this.agent = agent;
       this.area = area;
       this.merchantType = merchantType;
       this.merchantName = merchantName;
       this.address = address;
       this.beginDay = beginDay;
       this.activate = activate;
       this.transactionDetailses = transactionDetailses;
    }
   
    public int getMerchantId() {
        return this.merchantId;
    }
    
    public void setMerchantId(int merchantId) {
        this.merchantId = merchantId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public MerchantType getMerchantType() {
        return this.merchantType;
    }
    
    public void setMerchantType(MerchantType merchantType) {
        this.merchantType = merchantType;
    }
    public Serializable getMerchantName() {
        return this.merchantName;
    }
    
    public void setMerchantName(Serializable merchantName) {
        this.merchantName = merchantName;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Date getBeginDay() {
        return this.beginDay;
    }
    
    public void setBeginDay(Date beginDay) {
        this.beginDay = beginDay;
    }
    public Boolean getActivate() {
        return this.activate;
    }
    
    public void setActivate(Boolean activate) {
        this.activate = activate;
    }
    public Set<TransactionDetails> getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set<TransactionDetails> transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


