package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private int messageId;
     private MessageType messageType;
     private Integer userIdSend;
     private Integer userIdRecevie;
     private String messageContent;
     private Date time;

    public Message() {
    }

	
    public Message(int messageId) {
        this.messageId = messageId;
    }
    public Message(int messageId, MessageType messageType, Integer userIdSend, Integer userIdRecevie, String messageContent, Date time) {
       this.messageId = messageId;
       this.messageType = messageType;
       this.userIdSend = userIdSend;
       this.userIdRecevie = userIdRecevie;
       this.messageContent = messageContent;
       this.time = time;
    }
   
    public int getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }
    public MessageType getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }
    public Integer getUserIdSend() {
        return this.userIdSend;
    }
    
    public void setUserIdSend(Integer userIdSend) {
        this.userIdSend = userIdSend;
    }
    public Integer getUserIdRecevie() {
        return this.userIdRecevie;
    }
    
    public void setUserIdRecevie(Integer userIdRecevie) {
        this.userIdRecevie = userIdRecevie;
    }
    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


