package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MessageType generated by hbm2java
 */
public class MessageType  implements java.io.Serializable {


     private int messageTypeId;
     private Serializable messageTypeName;
     private Set<Message> messages = new HashSet<Message>(0);

    public MessageType() {
    }

	
    public MessageType(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    public MessageType(int messageTypeId, Serializable messageTypeName, Set<Message> messages) {
       this.messageTypeId = messageTypeId;
       this.messageTypeName = messageTypeName;
       this.messages = messages;
    }
   
    public int getMessageTypeId() {
        return this.messageTypeId;
    }
    
    public void setMessageTypeId(int messageTypeId) {
        this.messageTypeId = messageTypeId;
    }
    public Serializable getMessageTypeName() {
        return this.messageTypeName;
    }
    
    public void setMessageTypeName(Serializable messageTypeName) {
        this.messageTypeName = messageTypeName;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }




}


