package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private int privilegeId;
     private Serializable privilegeName;
     private Set<Account> accounts = new HashSet<Account>(0);

    public Privilege() {
    }

	
    public Privilege(int privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Privilege(int privilegeId, Serializable privilegeName, Set<Account> accounts) {
       this.privilegeId = privilegeId;
       this.privilegeName = privilegeName;
       this.accounts = accounts;
    }
   
    public int getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(int privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Serializable getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(Serializable privilegeName) {
        this.privilegeName = privilegeName;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


