package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ReportType generated by hbm2java
 */
public class ReportType  implements java.io.Serializable {


     private int reportTypeId;
     private Serializable reportTypeName;
     private Set<ReportMaster> reportMasters = new HashSet<ReportMaster>(0);
     private Set<ReportMerchant> reportMerchants = new HashSet<ReportMerchant>(0);
     private Set<ReportAgent> reportAgents = new HashSet<ReportAgent>(0);

    public ReportType() {
    }

	
    public ReportType(int reportTypeId) {
        this.reportTypeId = reportTypeId;
    }
    public ReportType(int reportTypeId, Serializable reportTypeName, Set<ReportMaster> reportMasters, Set<ReportMerchant> reportMerchants, Set<ReportAgent> reportAgents) {
       this.reportTypeId = reportTypeId;
       this.reportTypeName = reportTypeName;
       this.reportMasters = reportMasters;
       this.reportMerchants = reportMerchants;
       this.reportAgents = reportAgents;
    }
   
    public int getReportTypeId() {
        return this.reportTypeId;
    }
    
    public void setReportTypeId(int reportTypeId) {
        this.reportTypeId = reportTypeId;
    }
    public Serializable getReportTypeName() {
        return this.reportTypeName;
    }
    
    public void setReportTypeName(Serializable reportTypeName) {
        this.reportTypeName = reportTypeName;
    }
    public Set<ReportMaster> getReportMasters() {
        return this.reportMasters;
    }
    
    public void setReportMasters(Set<ReportMaster> reportMasters) {
        this.reportMasters = reportMasters;
    }
    public Set<ReportMerchant> getReportMerchants() {
        return this.reportMerchants;
    }
    
    public void setReportMerchants(Set<ReportMerchant> reportMerchants) {
        this.reportMerchants = reportMerchants;
    }
    public Set<ReportAgent> getReportAgents() {
        return this.reportAgents;
    }
    
    public void setReportAgents(Set<ReportAgent> reportAgents) {
        this.reportAgents = reportAgents;
    }




}


