package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * ReportMerchant generated by hbm2java
 */
public class ReportMerchant  implements java.io.Serializable {


     private int reportId;
     private ReportType reportType;
     private Integer merchantId;
     private Integer transactionType;
     private Serializable cardType;
     private BigDecimal saleAmount;
     private BigDecimal returnAmount;
     private Integer saleCount;
     private Integer returnCount;
     private BigDecimal netAmount;
     private Date reportDate;
     private Date fromDate;
     private Date toDate;

    public ReportMerchant() {
    }

	
    public ReportMerchant(int reportId) {
        this.reportId = reportId;
    }
    public ReportMerchant(int reportId, ReportType reportType, Integer merchantId, Integer transactionType, Serializable cardType, BigDecimal saleAmount, BigDecimal returnAmount, Integer saleCount, Integer returnCount, BigDecimal netAmount, Date reportDate, Date fromDate, Date toDate) {
       this.reportId = reportId;
       this.reportType = reportType;
       this.merchantId = merchantId;
       this.transactionType = transactionType;
       this.cardType = cardType;
       this.saleAmount = saleAmount;
       this.returnAmount = returnAmount;
       this.saleCount = saleCount;
       this.returnCount = returnCount;
       this.netAmount = netAmount;
       this.reportDate = reportDate;
       this.fromDate = fromDate;
       this.toDate = toDate;
    }
   
    public int getReportId() {
        return this.reportId;
    }
    
    public void setReportId(int reportId) {
        this.reportId = reportId;
    }
    public ReportType getReportType() {
        return this.reportType;
    }
    
    public void setReportType(ReportType reportType) {
        this.reportType = reportType;
    }
    public Integer getMerchantId() {
        return this.merchantId;
    }
    
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }
    public Integer getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(Integer transactionType) {
        this.transactionType = transactionType;
    }
    public Serializable getCardType() {
        return this.cardType;
    }
    
    public void setCardType(Serializable cardType) {
        this.cardType = cardType;
    }
    public BigDecimal getSaleAmount() {
        return this.saleAmount;
    }
    
    public void setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }
    public BigDecimal getReturnAmount() {
        return this.returnAmount;
    }
    
    public void setReturnAmount(BigDecimal returnAmount) {
        this.returnAmount = returnAmount;
    }
    public Integer getSaleCount() {
        return this.saleCount;
    }
    
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }
    public Integer getReturnCount() {
        return this.returnCount;
    }
    
    public void setReturnCount(Integer returnCount) {
        this.returnCount = returnCount;
    }
    public BigDecimal getNetAmount() {
        return this.netAmount;
    }
    
    public void setNetAmount(BigDecimal netAmount) {
        this.netAmount = netAmount;
    }
    public Date getReportDate() {
        return this.reportDate;
    }
    
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }




}


