package model;
// Generated Jun 10, 2017 12:17:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionDetails generated by hbm2java
 */
public class TransactionDetails  implements java.io.Serializable {


     private int id;
     private Merchant merchant;
     private TransactionType transactionType;
     private String product;
     private Double quantity;
     private BigDecimal unitPrice;
     private String cardNumber;
     private Date transactionTime;

    public TransactionDetails() {
    }

	
    public TransactionDetails(int id) {
        this.id = id;
    }
    public TransactionDetails(int id, Merchant merchant, TransactionType transactionType, String product, Double quantity, BigDecimal unitPrice, String cardNumber, Date transactionTime) {
       this.id = id;
       this.merchant = merchant;
       this.transactionType = transactionType;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.cardNumber = cardNumber;
       this.transactionTime = transactionTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public Date getTransactionTime() {
        return this.transactionTime;
    }
    
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }




}


