package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionDetails generated by hbm2java
 */
public class TransactionDetails  implements java.io.Serializable {


     private int id;
     private Card card;
     private Merchant merchant;
     private TransactionType transactionType;
     private String product;
     private Double quantity;
     private BigDecimal unitPrice;
     private Date transactionTime;

    public TransactionDetails() {
    }

	
    public TransactionDetails(int id) {
        this.id = id;
    }
    public TransactionDetails(int id, Card card, Merchant merchant, TransactionType transactionType, String product, Double quantity, BigDecimal unitPrice, Date transactionTime) {
       this.id = id;
       this.card = card;
       this.merchant = merchant;
       this.transactionType = transactionType;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.transactionTime = transactionTime;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Date getTransactionTime() {
        return this.transactionTime;
    }
    
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }




}


