package model;
// Generated Jun 7, 2017 9:47:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private int transactionTypeId;
     private Serializable transactionTypeName;
     private Set<TransactionDetails> transactionDetailses = new HashSet<TransactionDetails>(0);

    public TransactionType() {
    }

	
    public TransactionType(int transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }
    public TransactionType(int transactionTypeId, Serializable transactionTypeName, Set<TransactionDetails> transactionDetailses) {
       this.transactionTypeId = transactionTypeId;
       this.transactionTypeName = transactionTypeName;
       this.transactionDetailses = transactionDetailses;
    }
   
    public int getTransactionTypeId() {
        return this.transactionTypeId;
    }
    
    public void setTransactionTypeId(int transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }
    public Serializable getTransactionTypeName() {
        return this.transactionTypeName;
    }
    
    public void setTransactionTypeName(Serializable transactionTypeName) {
        this.transactionTypeName = transactionTypeName;
    }
    public Set<TransactionDetails> getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set<TransactionDetails> transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


