//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Activate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Master Master { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual Privilege Privilege { get; set; }
    }
}
