//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int PrivilegeId { get; set; }
        public string PrivilegeName { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
