//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Agents = new HashSet<Agent>();
            this.Masters = new HashSet<Master>();
            this.Merchants = new HashSet<Merchant>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> PrivilegeId { get; set; }
        public Nullable<bool> Activate { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Master> Masters { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual Privilege Privilege { get; set; }
    }
}
