//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Agent1 = new HashSet<Agent>();
            this.Merchants = new HashSet<Merchant>();
        }
    
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> ParentAgentId { get; set; }
        public Nullable<bool> Activate { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual ICollection<Agent> Agent1 { get; set; }
        public virtual Agent Agent2 { get; set; }
        public virtual Area Area { get; set; }
        public virtual Master Master { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
    }
}
