//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.Report_Agent = new HashSet<Report_Agent>();
            this.Report_Master = new HashSet<Report_Master>();
            this.Report_Merchant = new HashSet<Report_Merchant>();
        }
    
        public int ReportTypeId { get; set; }
        public string ReportTypeName { get; set; }
    
        public virtual ICollection<Report_Agent> Report_Agent { get; set; }
        public virtual ICollection<Report_Master> Report_Master { get; set; }
        public virtual ICollection<Report_Merchant> Report_Merchant { get; set; }
    }
}
