//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
