package entity;
// Generated Jun 12, 2017 12:53:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="Account"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class Account  implements java.io.Serializable {


     private int accountId;
     private Agent agent;
     private Master master;
     private Merchant merchant;
     private Privilege privilege;
     private String userName;
     private String password;
     private boolean activate;

    public Account() {
    }

	
    public Account(int accountId, Privilege privilege, String userName, String password, boolean activate) {
        this.accountId = accountId;
        this.privilege = privilege;
        this.userName = userName;
        this.password = password;
        this.activate = activate;
    }
    public Account(int accountId, Agent agent, Master master, Merchant merchant, Privilege privilege, String userName, String password, boolean activate) {
       this.accountId = accountId;
       this.agent = agent;
       this.master = master;
       this.merchant = merchant;
       this.privilege = privilege;
       this.userName = userName;
       this.password = password;
       this.activate = activate;
    }
   
     @Id 

    
    @Column(name="AccountId", unique=true, nullable=false)
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AgentId")
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MasterId")
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MerchantId")
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PrivilegeId", nullable=false)
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }

    
    @Column(name="UserName", nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="Password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Activate", nullable=false)
    public boolean isActivate() {
        return this.activate;
    }
    
    public void setActivate(boolean activate) {
        this.activate = activate;
    }




}


