package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountStatement generated by hbm2java
 */
@Entity
@Table(name="AccountStatement"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class AccountStatement {


     private int id;
     private Master master;
     private Integer cardId;
     private Integer month;
     private Integer year;
     private BigDecimal totalPrice;

    public AccountStatement() {
    }

	
    public AccountStatement(int id) {
        this.id = id;
    }
    public AccountStatement(int id, Master master, Integer cardId, Integer month, Integer year, BigDecimal totalPrice) {
       this.id = id;
       this.master = master;
       this.cardId = cardId;
       this.month = month;
       this.year = year;
       this.totalPrice = totalPrice;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MasterId")
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }

    
    @Column(name="CardId")
    public Integer getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

    
    @Column(name="Month")
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }

    
    @Column(name="Year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    
    @Column(name="TotalPrice", scale=4)
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }




}


