package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="Card"
    ,schema="dbo"
    ,catalog="CardProcessing"
    , uniqueConstraints = @UniqueConstraint(columnNames="CardNumber") 
)
public class Card  implements java.io.Serializable {


     private int cardId;
     private CardType cardType;
     private Master master;
     private String cardNumber;

    public Card() {
    }

	
    public Card(int cardId, String cardNumber) {
        this.cardId = cardId;
        this.cardNumber = cardNumber;
    }
    public Card(int cardId, CardType cardType, Master master, String cardNumber) {
       this.cardId = cardId;
       this.cardType = cardType;
       this.master = master;
       this.cardNumber = cardNumber;
    }
   
     @Id 

    
    @Column(name="CardId", unique=true, nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CardTypeId")
    public CardType getCardType() {
        return this.cardType;
    }
    
    public void setCardType(CardType cardType) {
        this.cardType = cardType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MasterId")
    public Master getMaster() {
        return this.master;
    }
    
    public void setMaster(Master master) {
        this.master = master;
    }

    
    @Column(name="CardNumber", unique=true, nullable=false, length=100)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }




}


