package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CardType generated by hbm2java
 */
@Entity
@Table(name="CardType"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class CardType  implements java.io.Serializable {


     private int cardTypeId;
     private Serializable cardTypeName;
     private Set<Card> cards = new HashSet<Card>(0);

    public CardType() {
    }

	
    public CardType(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }
    public CardType(int cardTypeId, Serializable cardTypeName, Set<Card> cards) {
       this.cardTypeId = cardTypeId;
       this.cardTypeName = cardTypeName;
       this.cards = cards;
    }
   
     @Id 

    
    @Column(name="CardTypeId", unique=true, nullable=false)
    public int getCardTypeId() {
        return this.cardTypeId;
    }
    
    public void setCardTypeId(int cardTypeId) {
        this.cardTypeId = cardTypeId;
    }

    
    @Column(name="CardTypeName")
    public Serializable getCardTypeName() {
        return this.cardTypeName;
    }
    
    public void setCardTypeName(Serializable cardTypeName) {
        this.cardTypeName = cardTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cardType")
    public Set<Card> getCards() {
        return this.cards;
    }
    
    public void setCards(Set<Card> cards) {
        this.cards = cards;
    }




}


