package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MerchantType generated by hbm2java
 */
@Entity
@Table(name="MerchantType"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class MerchantType {


     private int merchantTypeId;
     private String merchantTypeName;
     private Set<Merchant> merchants = new HashSet<Merchant>(0);

    public MerchantType() {
    }

	
    public MerchantType(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }
    public MerchantType(int merchantTypeId, String merchantTypeName, Set<Merchant> merchants) {
       this.merchantTypeId = merchantTypeId;
       this.merchantTypeName = merchantTypeName;
       this.merchants = merchants;
    }
   
     @Id 

    
    @Column(name="MerchantTypeId", unique=true, nullable=false)
    public int getMerchantTypeId() {
        return this.merchantTypeId;
    }
    
    public void setMerchantTypeId(int merchantTypeId) {
        this.merchantTypeId = merchantTypeId;
    }

    
    @Column(name="MerchantTypeName")
    public String getMerchantTypeName() {
        return this.merchantTypeName;
    }
    
    public void setMerchantTypeName(String merchantTypeName) {
        this.merchantTypeName = merchantTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="merchantType")
    public Set<Merchant> getMerchants() {
        return this.merchants;
    }
    
    public void setMerchants(Set<Merchant> merchants) {
        this.merchants = merchants;
    }




}


