package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name="Merchant"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class Merchant {


     private int merchantId;
     private Account account;
     private Agent agent;
     private Area area;
     private MerchantType merchantType;
     private String merchantName;
     private String address;
     private Date beginDay;
     private Boolean activate;
     private Set<TransactionDetails> transactionDetailses = new HashSet<TransactionDetails>(0);

    public Merchant() {
    }

	
    public Merchant(int merchantId) {
        this.merchantId = merchantId;
    }
    public Merchant(int merchantId, Account account, Agent agent, Area area, MerchantType merchantType, String merchantName, String address, Date beginDay, Boolean activate, Set<TransactionDetails> transactionDetailses) {
       this.merchantId = merchantId;
       this.account = account;
       this.agent = agent;
       this.area = area;
       this.merchantType = merchantType;
       this.merchantName = merchantName;
       this.address = address;
       this.beginDay = beginDay;
       this.activate = activate;
       this.transactionDetailses = transactionDetailses;
    }
   
     @Id 

    
    @Column(name="MerchantId", unique=true, nullable=false)
    public int getMerchantId() {
        return this.merchantId;
    }
    
    public void setMerchantId(int merchantId) {
        this.merchantId = merchantId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AccountId")
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AgentId")
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AreaId")
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MerchantTypeId")
    public MerchantType getMerchantType() {
        return this.merchantType;
    }
    
    public void setMerchantType(MerchantType merchantType) {
        this.merchantType = merchantType;
    }

    
    @Column(name="MerchantName")
    public String getMerchantName() {
        return this.merchantName;
    }
    
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BeginDay", length=10)
    public Date getBeginDay() {
        return this.beginDay;
    }
    
    public void setBeginDay(Date beginDay) {
        this.beginDay = beginDay;
    }

    
    @Column(name="Activate")
    public Boolean getActivate() {
        return this.activate;
    }
    
    public void setActivate(Boolean activate) {
        this.activate = activate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="merchant")
    public Set<TransactionDetails> getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set<TransactionDetails> transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


