package entity;
// Generated Jun 10, 2017 12:19:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="Message"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class Message  implements java.io.Serializable {


     private int messageId;
     private MessageType messageType;
     private Integer userIdSend;
     private Integer userIdRecevie;
     private String messageContent;
     private Date time;

    public Message() {
    }

	
    public Message(int messageId) {
        this.messageId = messageId;
    }
    public Message(int messageId, MessageType messageType, Integer userIdSend, Integer userIdRecevie, String messageContent, Date time) {
       this.messageId = messageId;
       this.messageType = messageType;
       this.userIdSend = userIdSend;
       this.userIdRecevie = userIdRecevie;
       this.messageContent = messageContent;
       this.time = time;
    }
   
     @Id 

    
    @Column(name="MessageId", unique=true, nullable=false)
    public int getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MessageTypeId")
    public MessageType getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }

    
    @Column(name="UserIdSend")
    public Integer getUserIdSend() {
        return this.userIdSend;
    }
    
    public void setUserIdSend(Integer userIdSend) {
        this.userIdSend = userIdSend;
    }

    
    @Column(name="UserIdRecevie")
    public Integer getUserIdRecevie() {
        return this.userIdRecevie;
    }
    
    public void setUserIdRecevie(Integer userIdRecevie) {
        this.userIdRecevie = userIdRecevie;
    }

    
    @Column(name="MessageContent")
    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Time", length=23)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


