package entity;
// Generated Jun 11, 2017 7:33:44 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="Privilege"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class Privilege {


     private int privilegeId;
     private String privilegeName;
     private Set<Account> accounts = new HashSet<Account>(0);

    public Privilege() {
    }

	
    public Privilege(int privilegeId) {
        this.privilegeId = privilegeId;
    }
    public Privilege(int privilegeId, String privilegeName, Set<Account> accounts) {
       this.privilegeId = privilegeId;
       this.privilegeName = privilegeName;
       this.accounts = accounts;
    }
   
     @Id 

    
    @Column(name="PrivilegeId", unique=true, nullable=false)
    public int getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(int privilegeId) {
        this.privilegeId = privilegeId;
    }

    
    @Column(name="PrivilegeName")
    public String getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="privilege")
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


