package entity;
// Generated Jun 10, 2017 12:19:01 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionType generated by hbm2java
 */
@Entity
@Table(name="TransactionType"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class TransactionType  implements java.io.Serializable {


     private int transactionTypeId;
     private Serializable transactionTypeName;
     private Set<TransactionDetails> transactionDetailses = new HashSet<TransactionDetails>(0);

    public TransactionType() {
    }

	
    public TransactionType(int transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }
    public TransactionType(int transactionTypeId, Serializable transactionTypeName, Set<TransactionDetails> transactionDetailses) {
       this.transactionTypeId = transactionTypeId;
       this.transactionTypeName = transactionTypeName;
       this.transactionDetailses = transactionDetailses;
    }
   
     @Id 

    
    @Column(name="TransactionTypeId", unique=true, nullable=false)
    public int getTransactionTypeId() {
        return this.transactionTypeId;
    }
    
    public void setTransactionTypeId(int transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }

    
    @Column(name="TransactionTypeName")
    public Serializable getTransactionTypeName() {
        return this.transactionTypeName;
    }
    
    public void setTransactionTypeName(Serializable transactionTypeName) {
        this.transactionTypeName = transactionTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactionType")
    public Set<TransactionDetails> getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set<TransactionDetails> transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


