package entity;
// Generated Jun 10, 2017 12:19:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionDetails generated by hbm2java
 */
@Entity
@Table(name="TransactionDetails"
    ,schema="dbo"
    ,catalog="CardProcessing"
)
public class TransactionDetails  implements java.io.Serializable {


     private int id;
     private Merchant merchant;
     private TransactionType transactionType;
     private String product;
     private Double quantity;
     private BigDecimal unitPrice;
     private String cardNumber;
     private Date transactionTime;

    public TransactionDetails() {
    }

	
    public TransactionDetails(int id) {
        this.id = id;
    }
    public TransactionDetails(int id, Merchant merchant, TransactionType transactionType, String product, Double quantity, BigDecimal unitPrice, String cardNumber, Date transactionTime) {
       this.id = id;
       this.merchant = merchant;
       this.transactionType = transactionType;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.cardNumber = cardNumber;
       this.transactionTime = transactionTime;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MerchantId")
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TransactionTypeId")
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="Product", length=150)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }

    
    @Column(name="Quantity", precision=53, scale=0)
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="UnitPrice", scale=4)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="CardNumber", length=100)
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TransactionTime", length=23)
    public Date getTransactionTime() {
        return this.transactionTime;
    }
    
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }




}


